### ISSUE TITLE
Cross browser cookie problem?

### ISSUE THREAD

**Issue by modules** [mvied/wordpress-https#27]
If i start from `http://domain.tld/blog` and want to login the form loads without an issue (through `https://ssl.webpack.de/domain.tld/b...`). After clicking sign-in i got a message that there is a problem with cookies. 

I suppose this is about crossdomain cookie?

I am able to login if https/ssl is disabled. Also checked if i disabled cookie support: thats not the case.

My setup:

WordPress is installed in a subdirectory /blog and reachable via main http://domain.tld/blog

The hoster provides an ssl proxy and the blog is accessible via https://ssl.hoster.tld/domain.tld/blog

Plugin Setup:

SSL Host: ssl.hoster.tld/domain.tld/blog
Force SSL Admin: enabled
Proxy: Yes

Everything else is default.

Debug outtput:

```
[BEGIN WordPress HTTPS Debug Log] (index):140
Version: 3.3.6 (index):141
HTTP URL: http://domain.tld/blog/ (index):142
HTTPS URL: https://ssl.webpack.de/domain.tld/blog/ (index):143
SSL: No (index):144
Diff Host: Yes (index):145
Subdomain: Yes (index):146
Proxy: Yes (index):147
Secure External URLs: [  ] (index):148
Unsecure External URLs: [  ] (index):149
[END WordPress HTTPS Debug Log] (index):150
event.returnValue is deprecated. Please use the standard event.preventDefault() instead.
```

Any help about it?

See also: http://wordpress.org/support/topic/crossdomain-issue?replies=3

**Comment by mvied** [comment]
The issue probably exists somewhere around here in the code: https://github.com/mvied/wordpress-https/blob/master/lib/WordPressHTTPS/Module/Core.php#L695
 
I've seen a couple of other users with issues related to these cookies in more complicated setups.

**Comment by mvied** [comment]
I've made this change in an attempt fix this issue and others. https://github.com/mvied/wordpress-https/commit/90a86cea0b40234322600d8c7da1a3443ab873b7
