### ISSUE TITLE
Add Updates to Wordpress Plugin Directory

### ISSUE THREAD

**Issue by d-simon** [mvied/wordpress-https#38]
It's a real pitty seeing the version on https://wordpress.org/plugins/wordpress-https/ being **3.3.6** and the last update **2 years** ago.

It'd be much appreciated if you @Mvied could start keeping the official Plugin Directory up to date again :+1:

**Comment by NetJon** [comment]
Amen!

Come back to us @Mvied !!

:-)

**Comment by lkraav** [comment]
Migrate over to iThemes Security, which has per-page SSL included, and is actively being worked on.

**Comment by NetJon** [comment]
Thanks Ikraav.  I'll look into that right now.

**Comment by d-simon** [comment]
Looks good, might try! Thanks lkraav :-)

**Comment by NetJon** [comment]
I used a combination of iThemes Security (ignoring it's other functions) and a plugin called SSLInsecure Content Fixer, and a few settings changes - voila!  My site is doing what I want.

Although, it would be nice to just use the one HTTPS plugin.

Perhaps it will be revived one day.

Right now, it fill up all the google searches for wordpress ssl solutions so it's hard to find other options.

**Comment by Tobias-Conrad** [comment]
please maintain the plugin, one plugin for each problem

**Comment by kristian-b** [comment]
It would be very nice, if the Wordpress Plugin directory can be updated with the current version from github.

**Comment by mvied** [comment]
It took me a while, but I released it. I was and am dreading what may come, haha. I'm currently working on a release that is purely on performance and automated testing so that I can corale this beast. Sorry for the wait!
