### ISSUE TITLE
Gravatar's domain replaced with WordPress's domain

### ISSUE THREAD

**Issue by TTouka** [mvied/wordpress-https#40]
Without wordpress-https, WordPress requests gravatar using non-secure URL: `http://0.gravatar.com/avatar/...`
But when wordpress-https is enabled, WordPress requests gravatar using its domain: `https://domain-of-wordpress/avatar/...`

This issue happens only with 3.4.0b, not happens with 3.3.6 installed via WordPress.

**Comment by mvied** [comment]
Please let me know if this is an issue in the latest version.

**Comment by mvied** [comment]
Fixed in latest.
