### ISSUE TITLE
Visit website generate 404 Not Found!

### ISSUE THREAD

**Issue by iqiqiqi** [mvied/wordpress-https#54]
I fill the SSL host after I install this plugin.After that,the homepage will generate this error:

## Not Found
The requested URL /index.php was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
Anyone meet this problem?

**Comment by mvied** [comment]
Make sure your HTTPS domain is functioning before you set your SSL Host. If you set it to something that is invalid, you will be auto-redirected to a 404 and will have to reset the plugin manually (see the [FAQ](https://wordpress.org/plugins/wordpress-https/#faq)).
