### ISSUE TITLE
Admin stylesheets not being rewritten by parser since 3.4.0

### ISSUE THREAD

**Issue by mvied** [mvied/wordpress-https#58]
Getting this result in admin panel when site URL is HTTP.
![image](https://user-images.githubusercontent.com/263531/34471003-e7a4c852-ef02-11e7-824d-870adad1b9cc.png)

**Comment by mvied** [comment]
Fixed in latest by parsing `content_url` properly.

**Comment by lawzava** [comment]
@mvied Any ETA when it may get released?
