### ISSUE TITLE
Call to a member function setPort() on boolean

### ISSUE THREAD

**Issue by neokoenig** [mvied/wordpress-https#61]
After upgrading to Version 3.4.1 I get:

`PHP Fatal error:  Call to a member function setPort() on boolean in /var/www/wordpress/wp-content/plugins/wordpress-https/lib/WordPressHTTPS.php on line 445`

PHP 5.6.32

**Comment by mvied** [comment]
@neokoenig Could you enable debug mode and show me a show me the browser's console so I can get a feel for your configuration? Have you used a custom port eve? Thanks!

Also, you can try resetting the plugin's cache and see if that resolves the issue.

**Comment by neokoenig** [comment]
Afraid I've had to roll back to 3.x on this (it was on a production box), so I can't really debug further without breaking it again.

I suspect the issue might have been a clash with Cloudflare's SSL: the reverse proxy nature of this might have caused the issue - I was only using the plugin to rewrite some troublesome plugins which didn't render resources using https.

**Comment by mvied** [comment]
@neokoenig No problem, but I do believe I've fixed it. Made a pretty goof when I rolled this one out that was most likely responsible. Understandable if you don't have time to fool with it. Thanks!
