### ISSUE TITLE
Redirect Loop

### ISSUE THREAD

**Issue by cornzie** [mvied/wordpress-https#66]
Hi,
Can anyone help?
i installed the wordpress-https plugin a few days ago and it worked very well up till now, but it locked me out of the entire website via a redirect loop.
what can i do?

**Comment by headstash** [comment]
Follow directions in FAQ to reset the plugin: https://wordpress.org/plugins/wordpress-https/#i%20can%E2%80%99t%20get%20into%20my%20admin%20panel.%20how%20do%20i%20fix%20it%3F
