### ISSUE TITLE
Force SSL Administration

### ISSUE THREAD

**Issue by shinshuri** [mvied/wordpress-https#67]
Hi:

I was attempting to test out the plugin for use and selected the checkbox for Force SSL Administration and saved the settings. Right after that I got locked out of my site and cannot access the WP Admin Dashboard. How can I regain access to the WP Admin Dashboard without disabling the plugin on the server? 

Can it be done database side? If so, what is the database name and how do I do it? Or what other method is available to help me to regain access to my WP Admin Dashboard. I really do want to keep using the plugin. I just need to disable this feature.

Thanks,
Shinshuri

**Comment by headstash** [comment]
Follow the directions here in the FAQ: https://wordpress.org/plugins/wordpress-https/#i%20can’t%20get%20into%20my%20admin%20panel.%20how%20do%20i%20fix%20it%3F
